name: Build rules files
on:
  workflow_dispatch:
  schedule:
    - cron: "30 23 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - "**/README.md"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set variables
        run: |
          echo "RELEASE_NAME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
        shell: bash

      - uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 0

      - name: Get country.mmdb geosite.dat geoip.dat relative files
        run: |
          curl -sSLO https://github.com/Yuu518/geoip/raw/release/Country.mmdb
          curl -sSLO https://github.com/Yuu518/geoip/raw/release/geoip.dat
          curl -sSLO https://github.com/Yuu518/sing-box-rules/raw/release/geosite.dat

      - name: Checkout Yuu518/meta-rules-converter
        uses: actions/checkout@v5.0.0
        with:
          repository: Yuu518/meta-rules-converter
          path: convert

      - name: Convert geo to mihomo-rules
        env:
          NO_SKIP: true
        run: |
          mkdir -p rule-set/mihomo/geosite && mkdir -p rule-set/mihomo/geoip
          cd convert
          go run ./ geosite -f ../geosite.dat -o ../rule-set/mihomo/geosite
          go run ./ geoip -f ../geoip.dat -o ../rule-set/mihomo/geoip
        
      - name: Convert geo to surge-rules
        env:
          NO_SKIP: true
        run: |
          mkdir -p rule-set/surge/geosite && mkdir -p rule-set/surge/geoip
          cd convert
          go run ./ geosite -f ../geosite.dat -o ../rule-set/surge/geosite -t surge
          go run ./ geoip -f ../geoip.dat -o ../rule-set/surge/geoip -t surge

      - name: Convert geo to loon-rules
        env:
          NO_SKIP: true
        run: |
          mkdir -p rule-set/loon/geosite && mkdir -p rule-set/loon/geoip
          cd convert
          go run ./ geosite -f ../geosite.dat -o ../rule-set/loon/geosite -t loon
          go run ./ geoip -f ../geoip.dat -o ../rule-set/loon/geoip -t loon

      - name: Git push assets to "rule-set" branch
        run: |
            cd rule-set || exit 1
            ls
            git init
            git config --local user.name "github-actions[bot]"
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git checkout -b rule-set
            git add .
            git commit -m "Released on ${RELEASE_NAME}"
            git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
            git push -f -u origin rule-set

      - name: Delete Workflow Runs
        uses: Mattraks/delete-workflow-runs@v2.0.6
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 1
          keep_minimum_runs: 1
